name: Super Linter workflow
on:
  issues:
    types: [closed, reopened]
jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3
        env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
